[package]
name = "modern_robotics_rs_hw"
version = "0.1.0"
edition = "2024"

[dependencies]
modern_robotics_rs = { git = "https://github.com/CottontailRabbit/modern_robotics_rs" }
nalgebra = "0.32"
plotters = "0.3"

